version: "3.9"  # optional since v1.27.0
services:
  sql:
    image: "mcr.microsoft.com/mssql/server:latest"
    container_name: sql_server2022_v2
    ports: # not actually needed, because the two services are on the same network.
      - "1403:1433" 
    healthcheck:
      test: "exit 0"
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=Forh@d123
  
  web_api:
    build: . # build the Docker image 
    depends_on:
      sql:
        condition: service_healthy
    environment:
        DatabaseServer: "172.16.7.19"
        DatabasePort: "1403"
        DatabaseUser: "SA"
        DatabasePassword: "Forh@d123"
        DatabaseName: "BooksStore"
    container_name: web_api_application_v2
    ports:
      - "8093:80"
  